# Internship Performance Evaluation Using Python,SQL & Power bi

# Introduction

This project focuses on analyzing and evaluating interns performance data using **SQL and Python**. The primary objective is to extract meaningful insights from structured review data stored in tabular format and transform it into an analytics-ready dataset.

The analysis covers weekly academic reviews, task performance, attendance, discipline, and evaluation outcomes such as **Week-Back decisions**. By leveraging SQL for querying and Python for data processing, this project aims to support data-driven decision-making and performance monitoring.

---

## Objective

The main objectives of this project are to:

- Transform and clean raw interns review data using **Python (Pandas & NumPy)**
- Perform structured analysis and querying using **SQL concepts**
- Identify performance trends, risks, and improvement areas among interns
- Evaluate advisor and reviewer assessment patterns
- Generate KPIs and insights suitable for **dashboards and reporting**

---

## Project Workflow

- Load and explore the raw interns review dataset
- Clean and preprocess data (handling missing values, data types, inconsistencies)
- Create derived metrics such as **average score** and **remarks categories**
- Prepare the dataset for SQL-based analysis and reporting
- Validate data quality and business rules

---

## Tools & Technologies Used

- **Python** (Pandas, NumPy)
- **SQL**
- **Jupyter Notebook**
- **Power BI / Visualization Tools** (optional)

### Dataset Description

- **_id** – Unique identifier for each record  
- **studentId** – Unique identifier associated with each student  
- **week** – Week number related to the review or record  
- **reviewDate** – Date when the review was conducted  
- **isScheduled** – Indicates whether the review was pre-scheduled (True/False)  
- **academic.review** – Student’s academic review score/feedback  
- **academic.task** – Student’s academic task score  
- **others.attendance** – Attendance record of the student for the given week  
- **others.discipline** – Discipline-related feedback for the student  
- **remark** – Additional reviewer comments or notes  
- **isDeleted** – Indicates whether this record is marked as deleted  
- **isWeekBack** – Flag indicating whether this review belongs to a previous week  
- **createdDate** – Timestamp when the record was first created  
- **updatedDate** – Timestamp when the record was last updated  
- **updatedBy** – User ID or system reference for who last updated the record  
- **student** – Student name or reference information  
- **advisor** – Name of the mentor/advisor assigned to the student  
- **batch** – Batch or group to which the student belongs  
- **joiningDate** – Date the student joined the program  
- **qualification** – Student’s educational qualification (e.g., BSc, BTech)  
- **advisorId** – Unique ID of the advisor  
- **domain** – Assigned learning domain or specialization  
- **status** – Current student status (Active, Inactive, Completed)  
- **branch._id** – Unique identifier of the branch  
- **branch.name** – Name of the branch  
- **branch.isDeleted** – Indicates whether the branch is marked as deleted  
- **branch.createdBy** – Person or system that created the branch record  
- **branch.createdDate** – Date when the branch record was created  
- **branch.updatedDate** – Date when the branch record was last updated  
- **branch.__v** – Version key of the branch record  
- **branch.updatedBy** – Person/system that last updated the branch  
- **reviewer** – Name of the person who conducted the review  
- **reviewerId** – Unique identifier of the reviewer  
- **createdBy** – Person/system that created this review record  
- **feeRecordId** – Identifier linking to the student’s fee record  
- **taskRecordId** – Identifier linking to a specific task  
- **courseRecord** – Reference to the student’s course/enrollment  
- **type** – Type of review record (weekly, monthly, etc.)

### Importing necessary libraries

In [5]:
import pandas as pd
import numpy as np

### Load data

In [2]:
df=pd.read_csv("Bridgeon-Dataset.csv")

### Analyze data

In [3]:
df.head()

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,remark,...,branch.updatedDate,branch.__v,branch.updatedBy,reviewer,reviewerId,createdBy,feeRecordId,taskRecordId,courseRecord,type
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,13-01-2024 05:30,False,7.5,7.5,9.2,8.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,Navas Angular,65742f98761942ac9d60b1ce,NaN,NaN,NaN,NaN,NaN
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,16-01-2024 05:30,False,4.5,4.5,6.4,7.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,SAFNA MOHD FAYAS,655af82fb0c2f1abb0ad6e04,655af82fb0c2f1abb0ad6e04,NaN,NaN,NaN,NaN
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,14-01-2024 05:30,False,8.0,8.0,7.5,8.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,Mohammed-Shakeeb-KP-DotNet-EXT,64d629447637697b68549ad8,64be3555b6dfaefb9e580bdd,NaN,NaN,NaN,NaN
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,08-01-2024 05:30,False,5.0,7.5,7.5,7.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,64be07ddb6dfaefb9e58051c,NaN,NaN,NaN,NaN
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,08-01-2024 05:30,False,3.0,4.0,6.7,7.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,64be07ddb6dfaefb9e58051c,659e7bea739d77b57ab615ed,NaN,NaN,NaN

In [4]:
df.head()

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,remark,...,branch.updatedDate,branch.__v,branch.updatedBy,reviewer,reviewerId,createdBy,feeRecordId,taskRecordId,courseRecord,type
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,13-01-2024 05:30,False,7.5,7.5,9.2,8.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,Navas Angular,65742f98761942ac9d60b1ce,NaN,NaN,NaN,NaN,NaN
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,16-01-2024 05:30,False,4.5,4.5,6.4,7.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,SAFNA MOHD FAYAS,655af82fb0c2f1abb0ad6e04,655af82fb0c2f1abb0ad6e04,NaN,NaN,NaN,NaN
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,14-01-2024 05:30,False,8.0,8.0,7.5,8.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,Mohammed-Shakeeb-KP-DotNet-EXT,64d629447637697b68549ad8,64be3555b6dfaefb9e580bdd,NaN,NaN,NaN,NaN
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,08-01-2024 05:30,False,5.0,7.5,7.5,7.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,64be07ddb6dfaefb9e58051c,NaN,NaN,NaN,NaN
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,08-01-2024 05:30,False,3.0,4.0,6.7,7.0,NaN,...,27-08-2024 11:20,0,64e30262a32a087d265bafb3,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,64be07ddb6dfaefb9e58051c,659e7bea739d77b57ab615ed,NaN,NaN,NaN

In [5]:
df.columns

Index(['_id', 'studentId', 'week', 'reviewDate', 'isScheduled',
       'academic.review', 'academic.task', 'others.attendance',
       'others.discipline', 'remark', 'isDeleted', 'isWeekBack', 'createdDate',
       'updatedDate', 'updatedBy', 'student', 'advisor', 'batch',
       'joiningDate', 'qualification', 'advisorId', 'domain', 'status',
       'branch._id', 'branch.name', 'branch.isDeleted', 'branch.createdBy',
       'branch.createdDate', 'branch.updatedDate', 'branch.__v',
       'branch.updatedBy', 'reviewer', 'reviewerId', 'createdBy',
       'feeRecordId', 'taskRecordId', 'courseRecord', 'type'],
      dtype='object')

In [6]:
df.shape

(14853, 38)

### Data Cleaning

#### 1) Removing irrelevant columns
Identify and remove any irrelevant columns that do not contribute to the analysis
_id,__v, isDeleted,feerecord_id, updatedDate, updatedBy, createdDate, feeRecordId, createdBy, taskRecordId.branchisdeleted,branch_id,branch_v,branchcreateddate,branchcreatedby

In [7]:
cols_to_drop = [
    '__v', 'isDeleted', 'createdBy', 'createdDate',
    'updatedDate', 'updatedBy',
    'feeRecordId', 'taskRecordId', 'courseRecord', 'type',
    'branch._id', 'branch.isDeleted', 'branch.createdBy',
    'branch.createdDate', 'branch.updatedDate',
    'branch.__v', 'branch.updatedBy',
    'remark'  
]

df = df.drop(columns=cols_to_drop, errors='ignore')

In [21]:
df

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,isWeekBack,...,advisor,batch,joiningDate,qualification,advisorId,domain,status,branch.name,reviewer,reviewerId
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,13-01-2024 05:30,False,7.5,7.5,9.2,8.0,False,...,SHAHIN SHAD.P.C,C16,18-09-2023 05:30,Btech others,64be3555b6dfaefb9e580bdd,Dot Net + Angular,Dropped,Kakkanchery,Navas Angular,65742f98761942ac9d60b1ce
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,16-01-2024 05:30,False,4.5,4.5,6.4,7.0,False,...,VISWAJITH.K,C16,18-09-2023 05:30,NaN,64afd95ed9e91e40b66fe1e9,Flutter,Dropped,Kakkanchery,SAFNA MOHD FAYAS,655af82fb0c2f1abb0ad6e04
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,14-01-2024 05:30,False,8.0,8.0,7.5,8.0,False,...,SHAHIN SHAD.P.C,C18,10-10-2023 05:30,Degree others,64be3555b6dfaefb9e580bdd,Java,Dropped,Kakkanchery,Mohammed-Shakeeb-KP-DotNet-EXT,64d629447637697b68549ad8
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,08-01-2024 05:30,False,5.0,7.5,7.5,7.0,False,...,ASWIN.P,C18,05-09-2023 05:30,Degree others,64be07ddb6dfaefb9e58051c,Dot Net,Placed,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,08-01-2024 05:30,False,3.0,4.0,6.7,7.0,True,...,SHIBIL HAROON,C18,06-09-2023 05:30,Plus two,66e92782c8124629a7fe9dac,Flutter,Terminated,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14848,6933d243035b5151d2c1ee0b,67f0e2d58355aa49d0d4db09,14,08-12-2025 05:30,True,0.0,0.0,0.0,0.0,False,...,SUBITHA.K,M22,12-05-2025 05:30,Plus two,66726c56e4057c63202f22dc,Data Analytics,Active,Manjeri,Nithin-DS-EXT,6889c66cc7a4d5c632d14984
14849,6933d310035b5151d2c20350,68353d6413cbecc34a6aa940,19,13-12-2025 05:30,True,0.0,0.0,0.0,0.0,False,...,VAISAKH,K9,10-06-2025 05:30,Degree CS,68bfb16e315689336574bca4,Python + React,Active,Kochi,Mohammed-Yassin-CK-Python-EXT,67060558cdb4912ca2a089dc
14850,6933d3e6035b5151d2c21846,680f1630d162b89b868c2252,19,08-12-2025 05:30,True,0.0,0.0,0.0,0.0,False,...,SUBITHA.K,M24,12-05-2025 05:30,Plus two,66726c56e4057c63202f22dc,Java + React,Active,Manjeri,Sai-Krishnan-Java-EXT,65742f37761942ac9d60b062
14851,6933d6f8035b5151d2c25588,67ad7c6196fbbdd338cf88de,20,06-12-2025 05:30,True,0.0,0.0,0.0,0.0,False,...,MUHAMMED ANSHID T,M20,09-04-2025 05:30,Degree others,67a49239fd6187f72e043df3,Python + React,Active,Manjeri,Aslam-Python-EXT,64fec6dc67ab7b3fb41c9ee6
14852,6933e0cd035b5151d2c30237,682d810927bb5ea6bc5bbc91,20,08-12-2025 05:30,True,0.0,0.0,0.0,0.0,False,...,SUBITHA.K,M24,11-06-2025 05:30,Plus two,66726c56e4057c63202f22dc,Golang,Active,Manjeri,Sreerag-TM-Golang-EXT,673588f087f743f3c92240b4

In [71]:
df.shape

(14854, 21)

In [8]:
df.reset_index(drop=True, inplace=True) #resets the index of the dataset, assigning a new sequential index to each row.
df.head()

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,isWeekBack,...,advisor,batch,joiningDate,qualification,advisorId,domain,status,branch.name,reviewer,reviewerId
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,13-01-2024 05:30,False,7.5,7.5,9.2,8.0,False,...,SHAHIN SHAD.P.C,C16,18-09-2023 05:30,Btech others,64be3555b6dfaefb9e580bdd,Dot Net + Angular,Dropped,Kakkanchery,Navas Angular,65742f98761942ac9d60b1ce
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,16-01-2024 05:30,False,4.5,4.5,6.4,7.0,False,...,VISWAJITH.K,C16,18-09-2023 05:30,NaN,64afd95ed9e91e40b66fe1e9,Flutter,Dropped,Kakkanchery,SAFNA MOHD FAYAS,655af82fb0c2f1abb0ad6e04
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,14-01-2024 05:30,False,8.0,8.0,7.5,8.0,False,...,SHAHIN SHAD.P.C,C18,10-10-2023 05:30,Degree others,64be3555b6dfaefb9e580bdd,Java,Dropped,Kakkanchery,Mohammed-Shakeeb-KP-DotNet-EXT,64d629447637697b68549ad8
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,08-01-2024 05:30,False,5.0,7.5,7.5,7.0,False,...,ASWIN.P,C18,05-09-2023 05:30,Degree others,64be07ddb6dfaefb9e58051c,Dot Net,Placed,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,08-01-2024 05:30,False,3.0,4.0,6.7,7.0,True,...,SHIBIL HAROON,C18,06-09-2023 05:30,Plus two,66e92782c8124629a7fe9dac,Flutter,Terminated,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14853 entries, 0 to 14852
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                14853 non-null  object
 1   studentId          14853 non-null  object
 2   week               14853 non-null  int64
 3   reviewDate         14853 non-null  object
 4   isScheduled        14853 non-null  bool
 5   academic.review    14853 non-null  float64
 6   academic.task      14853 non-null  float64
 7   others.attendance  14853 non-null  float64
 8   others.discipline  14853 non-null  float64
 9   isWeekBack         14853 non-null  bool
 10  student            14853 non-null  object
 11  advisor            14852 non-null  object
 12  batch              14852 non-null  object
 13  joiningDate        14853 non-null  object
 14  qualification      14657 non-null  object
 15  advisorId          14852 non-null  object
 16  domain             14853 non-null  object
 17  status             14853 non-null  object
 18  branch.name        14853 non-null  object
 19  reviewer           14463 non-null  object
 20  reviewerId         14463 non-null  object
dtypes: bool(2), float64(4), int64(1), object(14)
memory usage: 2.2+ MB

### checking missing values

In [10]:
df.isnull().sum()

_id                    0
studentId              0
week                   0
reviewDate             0
isScheduled            0
academic.review        0
academic.task          0
others.attendance      0
others.discipline      0
isWeekBack             0
student                0
advisor                1
batch                  1
joiningDate            0
qualification        196
advisorId              1
domain                 0
status                 0
branch.name            0
reviewer             390
reviewerId           390
dtype: int64

In [11]:
df['qualification'] = df['qualification'].fillna("Not Provided")
df['reviewer'] = df['reviewer'].fillna("UnknownReviewer")
df['reviewerId'] = df['reviewerId'].fillna("UnknownReviewerID")
df['advisor'] = df['advisor'].fillna("UnknownAdvisor")
df['advisorId'] = df['advisorId'].fillna("UnknownAdvisorID")
df['batch'] = df['batch'].fillna("UnknownBatch")

In [12]:
df.isnull().sum()

_id                  0
studentId            0
week                 0
reviewDate           0
isScheduled          0
academic.review      0
academic.task        0
others.attendance    0
others.discipline    0
isWeekBack           0
student              0
advisor              0
batch                0
joiningDate          0
qualification        0
advisorId            0
domain               0
status               0
branch.name          0
reviewer             0
reviewerId           0
dtype: int64

### Converting the datatypes

In [13]:
import pandas as pd

# 1. Convert date columns to datetime
df['reviewDate'] = pd.to_datetime(df['reviewDate'], errors='coerce')
df['joiningDate'] = pd.to_datetime(df['joiningDate'], errors='coerce')

# 2. Ensure numeric columns are numeric
num_cols = ['week', 'academic.review', 'academic.task',
            'others.attendance', 'others.discipline']
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 3. Convert ID columns to string (not category, because IDs are usually unique)
id_cols = ['_id', 'studentId', 'advisorId', 'reviewerId']
for col in id_cols:
    df[col] = df[col].astype('string')

# 4. Convert text / label columns to category
cat_cols = ['student', 'advisor', 'batch', 'qualification',
            'domain', 'status', 'branch.name', 'reviewer']
for col in cat_cols:
    df[col] = df[col].astype('category')

# 5. Check again
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14853 entries, 0 to 14852
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                14853 non-null  string
 1   studentId          14853 non-null  string
 2   week               14853 non-null  int64
 3   reviewDate         14853 non-null  datetime64[ns]
 4   isScheduled        14853 non-null  bool
 5   academic.review    14853 non-null  float64
 6   academic.task      14853 non-null  float64
 7   others.attendance  14853 non-null  float64
 8   others.discipline  14853 non-null  float64
 9   isWeekBack         14853 non-null  bool
 10  student            14853 non-null  category
 11  advisor            14853 non-null  category
 12  batch              14853 non-null  category
 13  joiningDate        14853 non-null  datetime64[ns]
 14  qualification      14853 non-null  category
 15  advisorId          14853 non-null  string
 16  domain             14853 non-null  category
 17  status             14853 non-null  category
 18  branch.name        14853 non-null  category
 19  reviewer           14853 non-null  category
 20  reviewerId         14853 non-null  string
dtypes: bool(2), category(8), datetime64[ns](2), float64(4), int64(1), string(4)
memory usage: 1.5 MB

C:\Users\shadi\AppData\Local\Temp\ipykernel_17900\3656963002.py:4: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['reviewDate'] = pd.to_datetime(df['reviewDate'], errors='coerce')
C:\Users\shadi\AppData\Local\Temp\ipykernel_17900\3656963002.py:5: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['joiningDate'] = pd.to_datetime(df['joiningDate'], errors='coerce')

### Checking duplicates

In [14]:
df.nunique()

_id                  14853
studentId             1164
week                    33
reviewDate             633
isScheduled              2
academic.review        132
academic.task           68
others.attendance      107
others.discipline       32
isWeekBack               2
student               1160
advisor                 36
batch                  134
joiningDate            206
qualification           11
advisorId               36
domain                  22
status                   7
branch.name              7
reviewer               123
reviewerId             123
dtype: int64

###### This is a interns performance data so there can have duplicate values.

### Data Transformation:
#### Adding New Column
##### 1)StdId
###### Map the studentId to the format CXXX_SYY, where:
###### CXXX is the batch code, formatted to 3 digits (e.g., C12 becomes C012, C13 becomes C013).
###### SYY is the sequential student number within the batch, formatted to two digits (e.g., S01, S02, etc.).

In [15]:
import re

# Step 1: Take unique studentId + batch pairs 
unique_students = df[['studentId', 'batch']].drop_duplicates().reset_index(drop=True)

# Step 2: Assign sequential number per batch
unique_students['seq'] = unique_students.groupby('batch').cumcount() + 1

# Step 3: Function: convert batch to CXXX 
def batch_to_code(batch):
    # extract digits (e.g., CDS3 -> 3, C12 -> 12)
    match = re.search(r'\d+', batch)
    num = match.group(0) if match else '0'
    return f"C{num.zfill(3)}"          

# Step 4: Create stdId = CXXX_SYY
unique_students['stdId'] = unique_students.apply(
    lambda row: f"{batch_to_code(row['batch'])}_S{str(row['seq']).zfill(2)}",
    axis=1
)

# Step 5: Map stdId back into the main dataframe
id_map = unique_students.set_index('studentId')['stdId'].to_dict()
df['stdId'] = df['studentId'].map(id_map)

# Show result 
print(df[['studentId', 'batch', 'stdId']].head())

                  studentId batch     stdId
0  64e7061a7a6a9fe0bb5fc3db   C16  C016_S01
1  64e7061a7a6a9fe0bb5fc3cd   C16  C016_S02
2  652c9fc02fe7f92814b33bae   C18  C018_S01
3  64f872c409bafce5474567c5   C18  C018_S02
4  64f877ec09bafce54745680d   C18  C018_S03

C:\Users\shadi\AppData\Local\Temp\ipykernel_17900\483347600.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  unique_students['seq'] = unique_students.groupby('batch').cumcount() + 1

In [33]:
df

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,isWeekBack,...,batch,joiningDate,qualification,advisorId,domain,status,branch.name,reviewer,reviewerId,stdId
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,2024-01-13 05:30:00,False,7.5,7.5,9.2,8.0,False,...,C16,2023-09-18 05:30:00,Btech others,64be3555b6dfaefb9e580bdd,Dot Net + Angular,Dropped,Kakkanchery,Navas Angular,65742f98761942ac9d60b1ce,C016_S01
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,2024-01-16 05:30:00,False,4.5,4.5,6.4,7.0,False,...,C16,2023-09-18 05:30:00,Not Provided,64afd95ed9e91e40b66fe1e9,Flutter,Dropped,Kakkanchery,SAFNA MOHD FAYAS,655af82fb0c2f1abb0ad6e04,C016_S02
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,2024-01-14 05:30:00,False,8.0,8.0,7.5,8.0,False,...,C18,2023-10-10 05:30:00,Degree others,64be3555b6dfaefb9e580bdd,Java,Dropped,Kakkanchery,Mohammed-Shakeeb-KP-DotNet-EXT,64d629447637697b68549ad8,C018_S01
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,2024-01-08 05:30:00,False,5.0,7.5,7.5,7.0,False,...,C18,2023-09-05 05:30:00,Degree others,64be07ddb6dfaefb9e58051c,Dot Net,Placed,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,C018_S02
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,2024-01-08 05:30:00,False,3.0,4.0,6.7,7.0,True,...,C18,2023-09-06 05:30:00,Plus two,66e92782c8124629a7fe9dac,Flutter,Terminated,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,C018_S03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14848,6933d243035b5151d2c1ee0b,67f0e2d58355aa49d0d4db09,14,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,M22,2025-05-12 05:30:00,Plus two,66726c56e4057c63202f22dc,Data Analytics,Active,Manjeri,Nithin-DS-EXT,6889c66cc7a4d5c632d14984,C022_S11
14849,6933d310035b5151d2c20350,68353d6413cbecc34a6aa940,19,2025-12-13 05:30:00,True,0.0,0.0,0.0,0.0,False,...,K9,2025-06-10 05:30:00,Degree CS,68bfb16e315689336574bca4,Python + React,Active,Kochi,Mohammed-Yassin-CK-Python-EXT,67060558cdb4912ca2a089dc,C009_S03
14850,6933d3e6035b5151d2c21846,680f1630d162b89b868c2252,19,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,M24,2025-05-12 05:30:00,Plus two,66726c56e4057c63202f22dc,Java + React,Active,Manjeri,Sai-Krishnan-Java-EXT,65742f37761942ac9d60b062,C024_S01
14851,6933d6f8035b5151d2c25588,67ad7c6196fbbdd338cf88de,20,2025-12-06 05:30:00,True,0.0,0.0,0.0,0.0,False,...,M20,2025-04-09 05:30:00,Degree others,67a49239fd6187f72e043df3,Python + React,Active,Manjeri,Aslam-Python-EXT,64fec6dc67ab7b3fb41c9ee6,C020_S05
14852,6933e0cd035b5151d2c30237,682d810927bb5ea6bc5bbc91,20,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,M24,2025-06-11 05:30:00,Plus two,66726c56e4057c63202f22dc,Golang,Active,Manjeri,Sreerag-TM-Golang-EXT,673588f087f743f3c92240b4,C024_S03

In [16]:
df.shape

(14853, 22)

##### 2) AdvisorId :
###### Map the advisor to the format A_XXX, where:
###### A represents the advisor.
###### XXX is the sequential advisor number, formatted to three digits (e.g., A_001, A_002, etc.).

In [17]:
# Step 1: Extract unique advisor names (ignore missing)
unique_advisors = df['advisor'].dropna().unique()

# Step 2: Create mapping A_001, A_002, A_003 
advisor_std_map = {
    advisor: f"A_{str(i + 1).zfill(3)}"
    for i, advisor in enumerate(unique_advisors)
}

# Step 3: Create new standardized advisor ID column
df['advisorStdId'] = df['advisor'].map(advisor_std_map)

# Step 4: Convert to string
df['advisorStdId'] = df['advisorStdId'].astype('string')

# Step 5: Handle rows where advisor is missing
df['advisorStdId'] = df['advisorStdId'].fillna("A_000")

In [36]:
df

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,isWeekBack,...,joiningDate,qualification,advisorId,domain,status,branch.name,reviewer,reviewerId,stdId,advisorStdId
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,2024-01-13 05:30:00,False,7.5,7.5,9.2,8.0,False,...,2023-09-18 05:30:00,Btech others,64be3555b6dfaefb9e580bdd,Dot Net + Angular,Dropped,Kakkanchery,Navas Angular,65742f98761942ac9d60b1ce,C016_S01,A_001
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,2024-01-16 05:30:00,False,4.5,4.5,6.4,7.0,False,...,2023-09-18 05:30:00,Not Provided,64afd95ed9e91e40b66fe1e9,Flutter,Dropped,Kakkanchery,SAFNA MOHD FAYAS,655af82fb0c2f1abb0ad6e04,C016_S02,A_002
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,2024-01-14 05:30:00,False,8.0,8.0,7.5,8.0,False,...,2023-10-10 05:30:00,Degree others,64be3555b6dfaefb9e580bdd,Java,Dropped,Kakkanchery,Mohammed-Shakeeb-KP-DotNet-EXT,64d629447637697b68549ad8,C018_S01,A_001
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,2024-01-08 05:30:00,False,5.0,7.5,7.5,7.0,False,...,2023-09-05 05:30:00,Degree others,64be07ddb6dfaefb9e58051c,Dot Net,Placed,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,C018_S02,A_003
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,2024-01-08 05:30:00,False,3.0,4.0,6.7,7.0,True,...,2023-09-06 05:30:00,Plus two,66e92782c8124629a7fe9dac,Flutter,Terminated,Kakkanchery,IRFAN HABEEB.P,64be3507b6dfaefb9e580b8f,C018_S03,A_004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14848,6933d243035b5151d2c1ee0b,67f0e2d58355aa49d0d4db09,14,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-05-12 05:30:00,Plus two,66726c56e4057c63202f22dc,Data Analytics,Active,Manjeri,Nithin-DS-EXT,6889c66cc7a4d5c632d14984,C022_S11,A_014
14849,6933d310035b5151d2c20350,68353d6413cbecc34a6aa940,19,2025-12-13 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-06-10 05:30:00,Degree CS,68bfb16e315689336574bca4,Python + React,Active,Kochi,Mohammed-Yassin-CK-Python-EXT,67060558cdb4912ca2a089dc,C009_S03,A_025
14850,6933d3e6035b5151d2c21846,680f1630d162b89b868c2252,19,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-05-12 05:30:00,Plus two,66726c56e4057c63202f22dc,Java + React,Active,Manjeri,Sai-Krishnan-Java-EXT,65742f37761942ac9d60b062,C024_S01,A_014
14851,6933d6f8035b5151d2c25588,67ad7c6196fbbdd338cf88de,20,2025-12-06 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-04-09 05:30:00,Degree others,67a49239fd6187f72e043df3,Python + React,Active,Manjeri,Aslam-Python-EXT,64fec6dc67ab7b3fb41c9ee6,C020_S05,A_019
14852,6933e0cd035b5151d2c30237,682d810927bb5ea6bc5bbc91,20,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-06-11 05:30:00,Plus two,66726c56e4057c63202f22dc,Golang,Active,Manjeri,Sreerag-TM-Golang-EXT,673588f087f743f3c92240b4,C024_S03,A_014

In [18]:
df.shape

(14853, 23)

##### 3) ReviewerId :
###### Map the reviewerName to the format R_XXX, where:
###### R represents the reviewer.
###### XXX is the sequential reviewer number, formatted to three digits (e.g., R_001, R_002, etc.).

In [19]:
#  Step 1: Take unique reviewer values (ignore NaN) ---
unique_reviewers = df[['reviewer']].drop_duplicates().reset_index(drop=True)

#  Step 2: Assign sequential number (starting at 1) ---
unique_reviewers['seq'] = unique_reviewers.reset_index().index + 1

#  Step 3: Create reviewerId = R_XXX
unique_reviewers['reviewerId'] = unique_reviewers['seq'].apply(
    lambda x: f"R_{str(x).zfill(3)}"
)

# Step 4: Map reviewerId back to main df
rev_map = unique_reviewers.set_index('reviewer')['reviewerId'].to_dict()
df['reviewerId'] = df['reviewer'].map(rev_map).astype('string')

# Step 5: Fill missing reviewer names with R_000 
df['reviewerId'] = df['reviewerId'].fillna("R_000")

# Optional: Check Result
print(df[['reviewer', 'reviewerId']].drop_duplicates().head(20))

                           reviewer reviewerId
0                     Navas Angular      R_001
1                  SAFNA MOHD FAYAS      R_002
2    Mohammed-Shakeeb-KP-DotNet-EXT      R_003
3                    IRFAN HABEEB.P      R_004
5                              Azad      R_005
6                   Shamnad Flutter      R_006
7                       VISWAJITH.K      R_007
8               Midhusha-Python-EXT      R_008
10          Siyahudheen-Flutter-EXT      R_009
16                  Shihad-MERN-EXT      R_010
21              MUHAMMED NAISAM.T.A      R_011
57            Sai-Krishnan-Java-EXT      R_012
64               Jibreel-Python-EXT      R_013
83                 Aslam-Python-EXT      R_014
105                 Jashfeer Golang      R_015
137                    Amar Flutter      R_016
162                 Shameem Flutter      R_017
245                Dilshad-MERN-EXT      R_018
275                 SHAHIN SHAD.P.C      R_019
286                  RABEEH EBRAHIM      R_020

In [38]:
df

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,isWeekBack,...,joiningDate,qualification,advisorId,domain,status,branch.name,reviewer,reviewerId,stdId,advisorStdId
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,2024-01-13 05:30:00,False,7.5,7.5,9.2,8.0,False,...,2023-09-18 05:30:00,Btech others,64be3555b6dfaefb9e580bdd,Dot Net + Angular,Dropped,Kakkanchery,Navas Angular,R_001,C016_S01,A_001
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,2024-01-16 05:30:00,False,4.5,4.5,6.4,7.0,False,...,2023-09-18 05:30:00,Not Provided,64afd95ed9e91e40b66fe1e9,Flutter,Dropped,Kakkanchery,SAFNA MOHD FAYAS,R_002,C016_S02,A_002
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,2024-01-14 05:30:00,False,8.0,8.0,7.5,8.0,False,...,2023-10-10 05:30:00,Degree others,64be3555b6dfaefb9e580bdd,Java,Dropped,Kakkanchery,Mohammed-Shakeeb-KP-DotNet-EXT,R_003,C018_S01,A_001
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,2024-01-08 05:30:00,False,5.0,7.5,7.5,7.0,False,...,2023-09-05 05:30:00,Degree others,64be07ddb6dfaefb9e58051c,Dot Net,Placed,Kakkanchery,IRFAN HABEEB.P,R_004,C018_S02,A_003
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,2024-01-08 05:30:00,False,3.0,4.0,6.7,7.0,True,...,2023-09-06 05:30:00,Plus two,66e92782c8124629a7fe9dac,Flutter,Terminated,Kakkanchery,IRFAN HABEEB.P,R_004,C018_S03,A_004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14848,6933d243035b5151d2c1ee0b,67f0e2d58355aa49d0d4db09,14,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-05-12 05:30:00,Plus two,66726c56e4057c63202f22dc,Data Analytics,Active,Manjeri,Nithin-DS-EXT,R_089,C022_S11,A_014
14849,6933d310035b5151d2c20350,68353d6413cbecc34a6aa940,19,2025-12-13 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-06-10 05:30:00,Degree CS,68bfb16e315689336574bca4,Python + React,Active,Kochi,Mohammed-Yassin-CK-Python-EXT,R_044,C009_S03,A_025
14850,6933d3e6035b5151d2c21846,680f1630d162b89b868c2252,19,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-05-12 05:30:00,Plus two,66726c56e4057c63202f22dc,Java + React,Active,Manjeri,Sai-Krishnan-Java-EXT,R_012,C024_S01,A_014
14851,6933d6f8035b5151d2c25588,67ad7c6196fbbdd338cf88de,20,2025-12-06 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-04-09 05:30:00,Degree others,67a49239fd6187f72e043df3,Python + React,Active,Manjeri,Aslam-Python-EXT,R_014,C020_S05,A_019
14852,6933e0cd035b5151d2c30237,682d810927bb5ea6bc5bbc91,20,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,False,...,2025-06-11 05:30:00,Plus two,66726c56e4057c63202f22dc,Golang,Active,Manjeri,Sreerag-TM-Golang-EXT,R_051,C024_S03,A_014

In [39]:
df.shape

(14853, 23)

#### Converting isWeekback to 0 & 1

In [20]:
# Mapping isweekback to 0 & 1
df['isWeekBack'] = df['isWeekBack'].astype(int)
df['isWeekBack'].value_counts()

isWeekBack
0    12028
1     2825
Name: count, dtype: int64

#### create a new column "remarks"

##### 1. 'Next week': isWeekBack == 0, avg score >= 7.5, attendance >= 6
##### 2. 'Next week-attendance concession': avg score >= 7.5, attendance < 6
##### 3. 'Next week-low score concession': avg score < 7.5, attendance >= 6
##### 4. 'Next week-concession': avg score < 7.5, attendance < 6
##### 5. 'Week back': isWeekBack == 1

In [21]:
import numpy as np
import pandas as pd

score_col1 = 'academic.review'
score_col2 = 'academic.task'
attendance_col = 'others.attendance'
weekback_col = 'isWeekBack'

df[score_col1] = pd.to_numeric(df[score_col1], errors='coerce')
df[score_col2] = pd.to_numeric(df[score_col2], errors='coerce')
df[attendance_col] = pd.to_numeric(df[attendance_col], errors='coerce')

df[weekback_col] = df[weekback_col].astype(int)

df['avgScore'] = df[[score_col1, score_col2]].mean(axis=1)

conditions = [
    (df[score_col1] == 0) & (df[score_col2] == 0),
    (df[weekback_col] == 1),
    (df['avgScore'] >= 7.5) & (df[attendance_col] >= 6),
    (df['avgScore'] >= 7.5) & (df[attendance_col] < 6),
    (df['avgScore'] < 7.5) & (df[attendance_col] >= 6),
    (df['avgScore'] < 7.5) & (df[attendance_col] < 6)
]

choices = [
    "Week back",
    "Week back",
    "Next week",
    "Next week - attendance concession",
    "Next week - low score concession",
    "Next week - concession"
]

df['remarks'] = np.select(conditions, choices, default="Unknown")

In [22]:
df

,_id,studentId,week,reviewDate,isScheduled,academic.review,academic.task,others.attendance,others.discipline,isWeekBack,...,advisorId,domain,status,branch.name,reviewer,reviewerId,stdId,advisorStdId,avgScore,remarks
0,65559b9c16868f1d18a4b363,64e7061a7a6a9fe0bb5fc3db,4,2024-01-13 05:30:00,False,7.5,7.5,9.2,8.0,0,...,64be3555b6dfaefb9e580bdd,Dot Net + Angular,Dropped,Kakkanchery,Navas Angular,R_001,C016_S01,A_001,7.50,Next week
1,656da3b9e355b12fb301f366,64e7061a7a6a9fe0bb5fc3cd,6,2024-01-16 05:30:00,False,4.5,4.5,6.4,7.0,0,...,64afd95ed9e91e40b66fe1e9,Flutter,Dropped,Kakkanchery,SAFNA MOHD FAYAS,R_002,C016_S02,A_002,4.50,Next week - low score concession
2,656eac45e355b12fb3028dcd,652c9fc02fe7f92814b33bae,5,2024-01-14 05:30:00,False,8.0,8.0,7.5,8.0,0,...,64be3555b6dfaefb9e580bdd,Java,Dropped,Kakkanchery,Mohammed-Shakeeb-KP-DotNet-EXT,R_003,C018_S01,A_001,8.00,Next week
3,65704761ce0f950eb8bd5e29,64f872c409bafce5474567c5,3,2024-01-08 05:30:00,False,5.0,7.5,7.5,7.0,0,...,64be07ddb6dfaefb9e58051c,Dot Net,Placed,Kakkanchery,IRFAN HABEEB.P,R_004,C018_S02,A_003,6.25,Next week - low score concession
4,6571467bce0f950eb8bdda53,64f877ec09bafce54745680d,3,2024-01-08 05:30:00,False,3.0,4.0,6.7,7.0,1,...,66e92782c8124629a7fe9dac,Flutter,Terminated,Kakkanchery,IRFAN HABEEB.P,R_004,C018_S03,A_004,3.50,Week back
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14848,6933d243035b5151d2c1ee0b,67f0e2d58355aa49d0d4db09,14,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,0,...,66726c56e4057c63202f22dc,Data Analytics,Active,Manjeri,Nithin-DS-EXT,R_089,C022_S11,A_014,0.00,Week back
14849,6933d310035b5151d2c20350,68353d6413cbecc34a6aa940,19,2025-12-13 05:30:00,True,0.0,0.0,0.0,0.0,0,...,68bfb16e315689336574bca4,Python + React,Active,Kochi,Mohammed-Yassin-CK-Python-EXT,R_044,C009_S03,A_025,0.00,Week back
14850,6933d3e6035b5151d2c21846,680f1630d162b89b868c2252,19,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,0,...,66726c56e4057c63202f22dc,Java + React,Active,Manjeri,Sai-Krishnan-Java-EXT,R_012,C024_S01,A_014,0.00,Week back
14851,6933d6f8035b5151d2c25588,67ad7c6196fbbdd338cf88de,20,2025-12-06 05:30:00,True,0.0,0.0,0.0,0.0,0,...,67a49239fd6187f72e043df3,Python + React,Active,Manjeri,Aslam-Python-EXT,R_014,C020_S05,A_019,0.00,Week back
14852,6933e0cd035b5151d2c30237,682d810927bb5ea6bc5bbc91,20,2025-12-08 05:30:00,True,0.0,0.0,0.0,0.0,0,...,66726c56e4057c63202f22dc,Golang,Active,Manjeri,Sreerag-TM-Golang-EXT,R_051,C024_S03,A_014,0.00,Week back

In [23]:
new_column_order = [
    'stdId',
    'studentId',
    'joiningDate',
    'qualification',
    'batch',

    # Advisor
    'advisorId',
    'advisorStdId',
    'advisor',

    # Week & Review Info
    'week',
    '_id',              
    'reviewDate',
    'reviewerId',
    'reviewer',

    # Scores
    'academic.review',
    'academic.task',
    'avgScore',

    # Attendance / Discipline
    'others.attendance',
    'others.discipline',

    # Status
    'isWeekBack',
    'remarks',
    'status',

    # Other fields
    'isScheduled',
    'student',
    'domain',
    'branch.name'
]

In [24]:

existing_cols = [col for col in new_column_order if col in df.columns]
remaining_cols = [col for col in df.columns if col not in existing_cols]

df = df[existing_cols + remaining_cols]

df.head()

,stdId,studentId,joiningDate,qualification,batch,advisorId,advisorStdId,advisor,week,_id,...,avgScore,others.attendance,others.discipline,isWeekBack,remarks,status,isScheduled,student,domain,branch.name
0,C016_S01,64e7061a7a6a9fe0bb5fc3db,2023-09-18 05:30:00,Btech others,C16,64be3555b6dfaefb9e580bdd,A_001,SHAHIN SHAD.P.C,4,65559b9c16868f1d18a4b363,...,7.50,9.2,8.0,0,Next week,Dropped,False,Neethu K Pushkaran,Dot Net + Angular,Kakkanchery
1,C016_S02,64e7061a7a6a9fe0bb5fc3cd,2023-09-18 05:30:00,Not Provided,C16,64afd95ed9e91e40b66fe1e9,A_002,VISWAJITH.K,6,656da3b9e355b12fb301f366,...,4.50,6.4,7.0,0,Next week - low score concession,Dropped,False,Muhammed Mubashir VP,Flutter,Kakkanchery
2,C018_S01,652c9fc02fe7f92814b33bae,2023-10-10 05:30:00,Degree others,C18,64be3555b6dfaefb9e580bdd,A_001,SHAHIN SHAD.P.C,5,656eac45e355b12fb3028dcd,...,8.00,7.5,8.0,0,Next week,Dropped,False,Josna Jose,Java,Kakkanchery
3,C018_S02,64f872c409bafce5474567c5,2023-09-05 05:30:00,Degree others,C18,64be07ddb6dfaefb9e58051c,A_003,ASWIN.P,3,65704761ce0f950eb8bd5e29,...,6.25,7.5,7.0,0,Next week - low score concession,Placed,False,Saleej K,Dot Net,Kakkanchery
4,C018_S03,64f877ec09bafce54745680d,2023-09-06 05:30:00,Plus two,C18,66e92782c8124629a7fe9dac,A_004,SHIBIL HAROON,3,6571467bce0f950eb8bdda53,...,3.50,6.7,7.0,1,Week back,Terminated,False,Rayees Anwar P,Flutter,Kakkanchery

#### rename columns

In [25]:
df= df.rename(columns={
    'academic.review':'review',
    'academic.task':'task',
    'others.attendance':'attendance',
    'others.discipline':'discipline'
})

In [26]:
df

,stdId,studentId,joiningDate,qualification,batch,advisorId,advisorStdId,advisor,week,_id,...,avgScore,attendance,discipline,isWeekBack,remarks,status,isScheduled,student,domain,branch.name
0,C016_S01,64e7061a7a6a9fe0bb5fc3db,2023-09-18 05:30:00,Btech others,C16,64be3555b6dfaefb9e580bdd,A_001,SHAHIN SHAD.P.C,4,65559b9c16868f1d18a4b363,...,7.50,9.2,8.0,0,Next week,Dropped,False,Neethu K Pushkaran,Dot Net + Angular,Kakkanchery
1,C016_S02,64e7061a7a6a9fe0bb5fc3cd,2023-09-18 05:30:00,Not Provided,C16,64afd95ed9e91e40b66fe1e9,A_002,VISWAJITH.K,6,656da3b9e355b12fb301f366,...,4.50,6.4,7.0,0,Next week - low score concession,Dropped,False,Muhammed Mubashir VP,Flutter,Kakkanchery
2,C018_S01,652c9fc02fe7f92814b33bae,2023-10-10 05:30:00,Degree others,C18,64be3555b6dfaefb9e580bdd,A_001,SHAHIN SHAD.P.C,5,656eac45e355b12fb3028dcd,...,8.00,7.5,8.0,0,Next week,Dropped,False,Josna Jose,Java,Kakkanchery
3,C018_S02,64f872c409bafce5474567c5,2023-09-05 05:30:00,Degree others,C18,64be07ddb6dfaefb9e58051c,A_003,ASWIN.P,3,65704761ce0f950eb8bd5e29,...,6.25,7.5,7.0,0,Next week - low score concession,Placed,False,Saleej K,Dot Net,Kakkanchery
4,C018_S03,64f877ec09bafce54745680d,2023-09-06 05:30:00,Plus two,C18,66e92782c8124629a7fe9dac,A_004,SHIBIL HAROON,3,6571467bce0f950eb8bdda53,...,3.50,6.7,7.0,1,Week back,Terminated,False,Rayees Anwar P,Flutter,Kakkanchery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14848,C022_S11,67f0e2d58355aa49d0d4db09,2025-05-12 05:30:00,Plus two,M22,66726c56e4057c63202f22dc,A_014,SUBITHA.K,14,6933d243035b5151d2c1ee0b,...,0.00,0.0,0.0,0,Week back,Active,True,Shamil Midhlaj,Data Analytics,Manjeri
14849,C009_S03,68353d6413cbecc34a6aa940,2025-06-10 05:30:00,Degree CS,K9,68bfb16e315689336574bca4,A_025,VAISAKH,19,6933d310035b5151d2c20350,...,0.00,0.0,0.0,0,Week back,Active,True,Aswin s,Python + React,Kochi
14850,C024_S01,680f1630d162b89b868c2252,2025-05-12 05:30:00,Plus two,M24,66726c56e4057c63202f22dc,A_014,SUBITHA.K,19,6933d3e6035b5151d2c21846,...,0.00,0.0,0.0,0,Week back,Active,True,MUHAMMED HADIL V,Java + React,Manjeri
14851,C020_S05,67ad7c6196fbbdd338cf88de,2025-04-09 05:30:00,Degree others,M20,67a49239fd6187f72e043df3,A_019,MUHAMMED ANSHID T,20,6933d6f8035b5151d2c25588,...,0.00,0.0,0.0,0,Week back,Active,True,Muhammed Jasil.U,Python + React,Manjeri
14852,C024_S03,682d810927bb5ea6bc5bbc91,2025-06-11 05:30:00,Plus two,M24,66726c56e4057c63202f22dc,A_014,SUBITHA.K,20,6933e0cd035b5151d2c30237,...,0.00,0.0,0.0,0,Week back,Active,True,Mohamed Junaid,Golang,Manjeri

In [27]:
df.to_csv("D:\downloads\live_project.csv")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\shadi\AppData\Local\Temp\ipykernel_17900\1952738992.py:1: SyntaxWarning: invalid escape sequence '\d'
  df.to_csv("D:\downloads\live_project.csv")

#### normalization of databse

##### 1)First Normal Form (1NF) Compliance

The cleaned dataset already satisfies 1NF because:

Every column contains atomic (indivisible) values
(e.g., qualification, advisor, review, attendance are single values, not lists).

There are no repeating groups or nested fields.

Each row represents a single review event for a student.

Conclusion: The dataset is fully compliant with 1NF.

##### 2)Partial Dependencies (Violation of 2NF)

Although the dataset satisfies 1NF, several attributes are dependent on only a part of the logical primary key or depend entirely on another non-key attribute.
Attributes such as advisor, reviewer, qualification, batch, and domain exhibit partial dependencies.
To achieve 2NF and remove redundancy, these attributes must be extracted into separate dimension tables, leaving the fact table with only foreign keys and measurable values.